
theme: jekyll-theme-hacker
title: Holland Reece Brown
#description: <a href="https://compbio.triiprograms.org">tri-i cbm</a> phd student<br>creagor at rockefeller dot edu<br><br><a href=#about-me>About me</a><br><a href=#publications>Publications</a><br><a href=#curriculum-vitae>Curriculum vitae</a>
#description: 
#logo: 