
theme: jekyll-theme-slate
title: Holland Reece Brown
description: Computational cognitive neuroscience research assistant at Weill Cornell Medicine <br><br><a href="https://weill.cornell.edu/units/sackler-institute-developmental-psychobiology">Institute of Developmental Psychobiology <br><a/><a href="https://psychiatry.weill.cornell.edu/weill-cornell-institute-geriatric-psychiatry">WCM Institute of Geriatric Psychiatry <br><a href="hob4003@med.cornell.edu">Email me<a/> <br><br><a href=#about-me>About me</a><br><a href=#code-samples>Code samples</a><br><a href=#curriculum-vitae>Curriculum vitae</a>
#logo: /images/HollandBrown.jpg
